"""Experiment 0016: reliable contract induction from novel documentation.

0015 showed that retrieval was not the problem (5/5) but free-form contract
extraction was (0/5).  This experiment isolates that boundary.  Mechanical
metadata is generated by AIR, while the model is measured on semantic fields
either in one shot, field by field, or with document evidence attached.

The retrieval, storage, sandbox, verifier, and 0015 synthesis boundaries stay
frozen.  Runtime JSON is resumable and intentionally ignored by Git.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
import hashlib
import json
import os
from pathlib import Path
import re
import statistics
import time
from typing import Any, Mapping, Sequence

import air_synth_012

from .exp009 import PythonFamily009, PythonGate009, run_python_gate_009, run_python_in_sandbox_009
from .exp010 import BASE_PYTHON_LIBRARY_010
from .exp011 import RETRIEVAL_PROMPT_HASH_011, RETRIEVAL_PROMPT_VERSION_011
from .exp012 import (
    ROBUSTNESS_SEEDS_012,
    _family_selected_doc_012,
    _retrieval_prompt_012,
    make_document_pool_012,
    make_robustness_families_012,
)
from .exp015 import (
    CONTRACT_PROMPT_HASH_015,
    CONTRACT_PROMPT_TEMPLATE_015,
    CONTRACT_PROMPT_VERSION_015,
    ModelLedger015,
    STRUCTURED_SYNTHESIS_PROMPT_HASH_015,
    build_structured_candidate_015,
    expected_contract_015,
    deterministic_skeleton_015,
)
from .model_client import LlamaCppClient, ModelUnavailable
from .neralis import parse_response
from .store import ExperimentStore


EXP016_VERSION = "air-016-v1"
MODEL_IDENTITY_016 = "SmolLM3-3B-GGUF-Q4_K_M; llama.cpp; CPU; context=4096"
CONTEXT_SIZE_016 = 4096
CONTRACT_SCHEMA_VERSION_016 = "air-contract-v1"
ARMS_016 = ("A_free_form", "B_structured_one_shot", "C_field_by_field", "D_evidence_grounded")
SEMANTIC_FIELDS_016 = (
    "operation_summary", "preconditions", "postconditions", "semantic_invariants",
    "ordering_constraints", "special_cases", "failure_behavior",
)
CRITICAL_FIELDS_016 = (
    "callable", "module", "signature", "input_type", "output_type",
    "operation_summary", "semantic_invariants",
)
CONTRACT_LIFECYCLE_016 = ("STRUCTURAL_ONLY", "PARTIAL", "COMPLETE", "REJECTED")
FAILURE_TAXONOMY_016 = (
    "retrieval_failure", "structural_metadata_failure", "semantic_extraction_failure",
    "unsupported_claim_failure", "evidence_failure", "incomplete_contract",
    "schema_failure", "oracle_downstream_failure", "extracted_contract_downstream_failure",
    "timeout", "safe_unknown",
)


STRUCTURED_SEMANTIC_PROMPT_TEMPLATE_016 = """Extract only the semantic part of an executable API contract.
Return exactly one JSON object with these fields and no others:
operation_summary, preconditions, postconditions, semantic_invariants,
ordering_constraints, special_cases, failure_behavior.
Use arrays of short strings for constraints and a short string for
operation_summary. If documentation does not establish a field, use ["unknown"]
or "unknown". Never invent a callable, module, import, or signature.

Documentation (the only authority):
{documentation}

Deterministic structural metadata supplied by AIR (do not change it):
{structural}
"""
STRUCTURED_SEMANTIC_PROMPT_VERSION_016 = "air-016-structured-semantic-v1"
STRUCTURED_SEMANTIC_PROMPT_HASH_016 = hashlib.sha256(STRUCTURED_SEMANTIC_PROMPT_TEMPLATE_016.encode("utf-8")).hexdigest()


FIELD_PROMPT_TEMPLATE_016 = """Extract exactly one semantic contract field from the documentation.
Return exactly one JSON object with fields: field, value. The value must be a
string for operation_summary and an array of short strings for every other
field. If the documentation does not establish the requested field, return
{{"field":"{field}","value":["unknown"]}} (or the string "unknown" for
operation_summary). Do not output implementation code or any structural metadata.

Requested field: {field}
Documentation:
{documentation}
"""
FIELD_PROMPT_VERSION_016 = "air-016-field-semantic-v1"
FIELD_PROMPT_HASH_016 = hashlib.sha256(FIELD_PROMPT_TEMPLATE_016.encode("utf-8")).hexdigest()


EVIDENCE_PROMPT_TEMPLATE_016 = """Extract exactly one semantic contract field and bind every claim to evidence.
Return exactly one JSON object with fields: field, value, evidence.
Evidence must be {{"doc_id": string, "quote_or_span": string}}. The quote/span
must be copied from the supplied document. If the field is not documented,
return value "unknown" or ["unknown"] and evidence {{"doc_id":"unknown","quote_or_span":"unknown"}}.
Do not output implementation code or structural metadata.

Requested field: {field}
Document id: {doc_id}
Documentation:
{documentation}
"""
EVIDENCE_PROMPT_VERSION_016 = "air-016-evidence-semantic-v1"
EVIDENCE_PROMPT_HASH_016 = hashlib.sha256(EVIDENCE_PROMPT_TEMPLATE_016.encode("utf-8")).hexdigest()


PROBE_PROMPT_TEMPLATE_016 = """Fill only the semantic body of transform(value: str) -> str.
Return exactly one JSON object: {{"semantic_body":"..."}}.
Use the documented API and the supplied semantic contract. Do not return imports,
a function definition, markdown, or explanation.

Documentation:
{documentation}
Semantic contract:
{semantic_contract}
"""
PROBE_PROMPT_VERSION_016 = "air-016-downstream-probe-v1"
PROBE_PROMPT_HASH_016 = hashlib.sha256(PROBE_PROMPT_TEMPLATE_016.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class StructuralMetadata016:
    module: str
    callable: str
    signature: str
    input_type: str
    output_type: str
    allowed_imports: tuple[str, ...]
    allowed_calls: tuple[str, ...]
    deterministic: bool
    side_effects: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class Evidence016:
    doc_id: str
    quote_or_span: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


@dataclass(frozen=True)
class CanonicalContract016:
    schema_version: str
    state: str
    structural: StructuralMetadata016
    semantic: dict[str, Any]
    evidence: dict[str, Evidence016 | None]
    unknown_fields: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "state": self.state,
            "structural": self.structural.to_dict(),
            "semantic": self.semantic,
            "evidence": {key: (value.to_dict() if value else None) for key, value in self.evidence.items()},
            "unknown_fields": list(self.unknown_fields),
        }


def canonical_json_016(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _parse_model_json_016(text: str) -> dict[str, Any] | None:
    """Prefer the complete object; the legacy parser returns nested last objects."""
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = re.sub(r"^```(?:json)?\s*", "", stripped, count=1, flags=re.I)
        stripped = re.sub(r"\s*```$", "", stripped, count=1)
    try:
        value = json.loads(stripped)
    except json.JSONDecodeError:
        value = None
        decoder = json.JSONDecoder()
        for index, character in enumerate(stripped):
            if character != "{":
                continue
            try:
                candidate, _ = decoder.raw_decode(stripped[index:])
            except json.JSONDecodeError:
                continue
            if isinstance(candidate, dict):
                value = candidate
                break
        if value is None:
            value = parse_response(text)
    return value if isinstance(value, dict) else None


def structural_metadata_016(family: PythonFamily009) -> StructuralMetadata016:
    """Derive mechanical facts from the known package manifest, never the model."""
    operation = family.family_id.rsplit("-", 1)[-1]
    return StructuralMetadata016(
        module="air_synth_012", callable="transform", signature="transform(value: str) -> str",
        input_type="str", output_type="str", allowed_imports=("air_synth_012",),
        allowed_calls=(operation,), deterministic=True, side_effects="none",
    )


def _family_kind_variant_016(family: PythonFamily009) -> tuple[str, int]:
    parts = family.family_id.split("-")
    # air012-1201-shards-op_xxxxxxx
    seed = int(parts[1])
    return parts[2], air_synth_012.SEEDS_012.index(seed)


def _family_generation_seed_016(family: PythonFamily009) -> int:
    return int(family.family_id.split("-")[1])


def semantic_ground_truth_016(family: PythonFamily009) -> dict[str, Any]:
    """Structured, deterministic ground truth kept out of every model prompt."""
    kind, variant = _family_kind_variant_016(family)
    operation = family.family_id.rsplit("-", 1)[-1]
    delimiter = ("|", "~", "^")[variant]
    factor = (3, 5, 7)[variant]
    offset = (1, 2, 4)[variant]
    separator = ("/", ":", ".")[variant]
    if kind == "shards":
        summary = f"split:{delimiter};reverse_shard_order;reverse_uppercase;join:{delimiter}"
        order = ["reverse shard order", "preserve delimiter"]
        special = ["empty shards remain representable"]
    elif kind == "numbers":
        summary = f"parse comma integers;map n*{factor}+{offset};deduplicate;sort descending;join:semicolon"
        order = ["deduplicate before descending sort", "join with semicolon"]
        special = ["whitespace around integers is accepted"]
    elif kind == "object":
        direction = "descending" if variant % 2 else "ascending"
        summary = f"parse JSON object;order keys {direction};join key=value with vertical bar"
        order = [f"keys {direction}", "join with vertical bar"]
        special = ["JSON values are rendered in their parsed representation"]
    elif kind == "mixed":
        summary = f"split final hash;rotate left {variant + 1};reverse uppercase text;append scaled number"
        order = ["split at final hash", "rotate before reverse", "append numeric suffix"]
        special = ["numeric part is transformed by multiplication and offset"]
    else:
        summary = f"run length encode consecutive characters;join groups with {separator}"
        order = ["group consecutive equal characters", "join groups in input order"]
        special = ["empty input returns empty string"]
    return {
        "operation_summary": summary,
        "preconditions": ["input is a string", "input follows the documented family format"],
        "postconditions": ["return value is a string", "transformation is deterministic"],
        "semantic_invariants": [f"operation={operation}", f"family={kind}", "same input yields same output"],
        "ordering_constraints": order,
        "special_cases": special,
        "failure_behavior": ["undocumented or invalid inputs are not silently reinterpreted"],
    }


def make_contract_families_016() -> tuple[PythonFamily009, ...]:
    """Five 0015 families plus three independent seed-1202 families."""
    selected: list[PythonFamily009] = []
    selected.extend(make_robustness_families_012(1201))
    selected.extend(make_robustness_families_012(1202)[:3])
    return tuple(selected)


def _safe_model_json_016(client: Any, store: ExperimentStore, ledger: ModelLedger015, *, kind: str,
                         prompt: str, max_tokens: int, seed: int, arm: str,
                         prompt_version: str, prompt_sha256: str, metadata: Mapping[str, Any] | None = None) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    started = time.perf_counter()
    try:
        completion = client.chat_json(prompt, max_tokens=max_tokens, seed=seed)
        payload = _parse_model_json_016(completion.text)
        elapsed = completion.elapsed_seconds
        prompt_tokens = completion.prompt_tokens or 0
        generated_tokens = completion.generated_tokens or 0
        error = None
        response = completion.text
    except ModelUnavailable as exc:
        payload = None
        elapsed = getattr(client, "timeout_seconds", time.perf_counter() - started)
        prompt_tokens = generated_tokens = 0
        error = str(exc)
        response = json.dumps({"runtime_error": error})
    ledger.observe(prompt=prompt, elapsed=elapsed, prompt_tokens=prompt_tokens,
                   output_tokens=generated_tokens, timeout=error is not None, arm=arm)
    store.record_run(kind=kind, prompt=prompt, response=response, elapsed_seconds=elapsed,
                     prompt_tokens=prompt_tokens, generated_tokens=generated_tokens, passed=None,
                     metadata={**dict(metadata or {}), "arm": arm, "prompt_version": prompt_version,
                               "prompt_sha256": prompt_sha256, "runtime_error": error, "seed": seed})
    return (payload if isinstance(payload, dict) else None), {
        "elapsed_seconds": elapsed, "prompt_tokens": prompt_tokens,
        "generated_tokens": generated_tokens, "runtime_error": error,
    }


def _field_value(payload: Mapping[str, Any] | None, field_name: str) -> Any:
    if not isinstance(payload, Mapping):
        return None
    if field_name in payload:
        return payload[field_name]
    if payload.get("field") == field_name:
        return payload.get("value")
    if "value" in payload and len(payload) <= 3:
        return payload.get("value")
    return None


def _evidence_value(payload: Mapping[str, Any] | None) -> Evidence016 | None:
    if not isinstance(payload, Mapping) or not isinstance(payload.get("evidence"), Mapping):
        return None
    item = payload["evidence"]
    doc_id = item.get("doc_id") if isinstance(item.get("doc_id"), str) else None
    quote = item.get("quote_or_span") if isinstance(item.get("quote_or_span"), str) else None
    return Evidence016(doc_id, quote) if doc_id is not None and quote is not None else None


def _flatten_text(value: Any) -> str:
    if isinstance(value, str):
        return value.lower()
    if isinstance(value, Mapping):
        return " ".join(f"{key} {item}" for key, item in value.items()).lower()
    if isinstance(value, (list, tuple)):
        return " ".join(_flatten_text(item) for item in value)
    return str(value).lower()


def _semantic_required_tokens_016(family: PythonFamily009, field_name: str) -> tuple[str, ...]:
    kind, _ = _family_kind_variant_016(family)
    if field_name == "operation_summary":
        by_kind = {
            "shards": ("split", "reverse", "uppercase", "join"),
            "numbers": ("integer", "map", "deduplicate", "sort", "semicolon"),
            "object": ("json", "key", "join"),
            "mixed": ("hash", "rotate", "reverse", "append"),
            "runs": ("run", "length", "consecutive", "join"),
        }
        # The semantic summary describes behavior; the opaque callable name is
        # checked separately by the structural contract and invariant fields.
        return by_kind[kind]
    if field_name == "preconditions":
        return ("string",)
    if field_name == "postconditions":
        return ("string", "deterministic")
    if field_name == "semantic_invariants":
        return ("operation", kind)
    if field_name == "ordering_constraints":
        by_kind = {
            "shards": ("reverse", "delimiter"),
            "numbers": ("deduplicate", "sort"),
            "object": ("key",),
            "mixed": ("split", "rotate"),
            "runs": ("order",),
        }
        return by_kind[kind]
    if field_name == "special_cases":
        by_kind = {
            "shards": ("empty", "shard"),
            "numbers": ("whitespace", "integer"),
            "object": ("json", "value"),
            "mixed": ("numeric", "transformed"),
            "runs": ("empty", "input"),
        }
        return by_kind[kind]
    return ("invalid",) if field_name == "failure_behavior" else ("unknown",)


def semantic_field_correct_016(family: PythonFamily009, field_name: str, value: Any) -> bool:
    """Verify structured meaning without demanding one prose string."""
    if value is None or (isinstance(value, str) and value.strip().lower() == "unknown"):
        return False
    if isinstance(value, list) and any(str(item).strip().lower() == "unknown" for item in value):
        return False
    text = _flatten_text(value)
    tokens = _semantic_required_tokens_016(family, field_name)
    # Failure behavior is documented as a conservative constraint, not a verbatim phrase.
    if field_name == "failure_behavior":
        return any(word in text for word in ("invalid", "undocumented", "error", "not silently"))
    return all(token in text for token in tokens)


def _structural_field_value_016(structural: StructuralMetadata016, field_name: str) -> Any:
    if field_name == "allowed_calls":
        return list(structural.allowed_calls)
    if field_name == "allowed_imports":
        return list(structural.allowed_imports)
    return getattr(structural, field_name)


def _legacy_semantic_payload_016(payload: Mapping[str, Any] | None) -> dict[str, Any]:
    if not isinstance(payload, Mapping):
        return {}
    result: dict[str, Any] = {}
    for field_name in SEMANTIC_FIELDS_016:
        value = _field_value(payload, field_name)
        if value is not None:
            result[field_name] = value
    # 0015 called this field known_invariants; accepting the name is part of
    # measuring the old baseline, not of the canonical schema.
    if "semantic_invariants" not in result and "known_invariants" in payload:
        result["semantic_invariants"] = payload["known_invariants"]
    return result


def _validate_evidence_016(evidence: Evidence016 | None, doc_id: str, documentation: str) -> bool:
    if evidence is None or evidence.doc_id in {"unknown", ""} or evidence.doc_id != doc_id:
        return False
    if evidence.quote_or_span in {"unknown", ""}:
        return False
    # A span may be a line marker; otherwise require an actual document substring.
    if evidence.quote_or_span in documentation:
        return True
    return bool(re.fullmatch(r"lines?\s*\d+(?:[-:]\d+)?", evidence.quote_or_span.strip(), re.I))


def _canonicalize_016(*, arm: str, family: PythonFamily009, payload: Mapping[str, Any] | None,
                      semantic_values: Mapping[str, Any], semantic_evidence: Mapping[str, Evidence016 | None],
                      doc_id: str, documentation: str, malformed: bool = False) -> dict[str, Any]:
    structural = structural_metadata_016(family)
    raw = payload if isinstance(payload, Mapping) else {}
    unknown = tuple(sorted(set(raw) - {
        "module", "callable", "signature", "input_type", "output_type", "allowed_imports",
        "allowed_calls", "allowed_import_members", "allowed_call_names", "deterministic",
        "allowed_attrs", "side_effects", "side_effect_policy", "return_requirements", "known_invariants",
        *SEMANTIC_FIELDS_016, "field", "value", "evidence",
    }))
    structural_values: dict[str, Any] = {}
    for field_name in ("module", "callable", "signature", "input_type", "output_type", "allowed_imports", "allowed_calls", "deterministic", "side_effects"):
        if arm == "A_free_form":
            value = raw.get(field_name)
            if field_name == "allowed_calls" and value is None:
                value = raw.get("allowed_call_names") or raw.get("allowed_import_members")
            if field_name == "side_effects" and value is None:
                value = raw.get("side_effect_policy")
            structural_values[field_name] = value
        else:
            structural_values[field_name] = _structural_field_value_016(structural, field_name)
    structural_accuracy = {
        field_name: structural_values[field_name] == _structural_field_value_016(structural, field_name)
        for field_name in ("module", "callable", "signature", "input_type", "output_type", "allowed_imports", "allowed_calls", "deterministic", "side_effects")
    }
    semantic_accuracy = {field_name: semantic_field_correct_016(family, field_name, semantic_values.get(field_name)) for field_name in SEMANTIC_FIELDS_016}
    evidence_correct = {field_name: _validate_evidence_016(semantic_evidence.get(field_name), doc_id, documentation) for field_name in SEMANTIC_FIELDS_016} if arm == "D_evidence_grounded" else {}
    unsupported = 0
    for field_name, value in semantic_values.items():
        if isinstance(value, (str, list, dict)) and ("hallucinated" in _flatten_text(value) or "undocumented_import" in _flatten_text(value)):
            unsupported += 1
    unsupported += len(unknown)
    malformed = malformed or bool(unknown)
    structural_ok = all(structural_accuracy.values())
    semantic_ok = all(semantic_accuracy.values())
    evidence_ok = all(evidence_correct.values()) if arm == "D_evidence_grounded" else True
    if malformed:
        state = "REJECTED"
    elif structural_ok and semantic_ok and evidence_ok:
        state = "COMPLETE"
    elif structural_ok and not any(semantic_accuracy.values()):
        state = "STRUCTURAL_ONLY"
    else:
        state = "PARTIAL"
    critical_values = {**structural_accuracy, "operation_summary": semantic_accuracy["operation_summary"], "semantic_invariants": semantic_accuracy["semantic_invariants"]}
    return {
        "state": state, "structural": structural.to_dict(), "structural_accuracy": structural_accuracy,
        "semantic": dict(semantic_values), "semantic_accuracy": semantic_accuracy,
        "evidence": {key: (value.to_dict() if value else None) for key, value in semantic_evidence.items()},
        "evidence_correct": evidence_correct, "critical_field_accuracy": sum(critical_values.values()) / len(critical_values),
        "complete_valid": state == "COMPLETE", "unsupported_claims": unsupported,
        "unknown_or_abstentions": sum(_flatten_text(value) == "unknown" or "unknown" in _flatten_text(value) for value in semantic_values.values()),
        "unknown_fields": list(unknown), "malformed": malformed,
    }


def _empty_semantic_016() -> dict[str, Any]:
    return {field_name: None for field_name in SEMANTIC_FIELDS_016}


def _run_baseline_contract_016(client: Any, store: ExperimentStore, ledger: ModelLedger015,
                               family: PythonFamily009, selected: PythonFamily009, seed: int) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    prompt = CONTRACT_PROMPT_TEMPLATE_015.format(documentation=selected.api_docs, declared_contract=selected.contract)
    return _safe_model_json_016(client, store, ledger, kind=f"air-016:A:{family.family_id}", prompt=prompt,
                                max_tokens=256, seed=seed, arm="A_free_form", prompt_version=CONTRACT_PROMPT_VERSION_015,
                                prompt_sha256=CONTRACT_PROMPT_HASH_015, metadata={"family_id": family.family_id})


def _run_one_shot_016(client: Any, store: ExperimentStore, ledger: ModelLedger015,
                      family: PythonFamily009, selected: PythonFamily009, seed: int) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    structural = structural_metadata_016(family)
    prompt = STRUCTURED_SEMANTIC_PROMPT_TEMPLATE_016.format(documentation=selected.api_docs, structural=canonical_json_016(structural.to_dict()))
    return _safe_model_json_016(client, store, ledger, kind=f"air-016:B:{family.family_id}", prompt=prompt,
                                max_tokens=256, seed=seed, arm="B_structured_one_shot", prompt_version=STRUCTURED_SEMANTIC_PROMPT_VERSION_016,
                                prompt_sha256=STRUCTURED_SEMANTIC_PROMPT_HASH_016, metadata={"family_id": family.family_id})


def _run_field_arm_016(client: Any, store: ExperimentStore, ledger: ModelLedger015, family: PythonFamily009,
                       selected: PythonFamily009, seed: int, evidence_mode: bool) -> tuple[dict[str, Any], dict[str, Any]]:
    values: dict[str, Any] = {}
    evidences: dict[str, Evidence016 | None] = {}
    attempts: list[dict[str, Any]] = []
    for index, field_name in enumerate(SEMANTIC_FIELDS_016):
        if evidence_mode:
            pool, doc_id = make_document_pool_012(family, 10, _family_generation_seed_016(family))
            # The selected document ID is injected by the caller's retrieval result;
            # field prompt evidence must still name the actual selected record.
            doc_id = next((record["doc_id"] for record in pool if record["text"] == selected.api_docs), "unknown")
            prompt = EVIDENCE_PROMPT_TEMPLATE_016.format(field=field_name, doc_id=doc_id, documentation=selected.api_docs)
            version, prompt_hash, arm = EVIDENCE_PROMPT_VERSION_016, EVIDENCE_PROMPT_HASH_016, "D_evidence_grounded"
            kind = f"air-016:D:{family.family_id}:{field_name}"
        else:
            prompt = FIELD_PROMPT_TEMPLATE_016.format(field=field_name, documentation=selected.api_docs)
            version, prompt_hash, arm = FIELD_PROMPT_VERSION_016, FIELD_PROMPT_HASH_016, "C_field_by_field"
            kind = f"air-016:C:{family.family_id}:{field_name}"
        payload, telemetry = _safe_model_json_016(client, store, ledger, kind=kind, prompt=prompt, max_tokens=160,
                                                  seed=seed + index, arm=arm, prompt_version=version,
                                                  prompt_sha256=prompt_hash, metadata={"family_id": family.family_id, "field": field_name})
        values[field_name] = _field_value(payload, field_name)
        evidences[field_name] = _evidence_value(payload)
        attempts.append({"field": field_name, "payload": payload, "evidence": evidences[field_name].to_dict() if evidences[field_name] else None, **telemetry})
    return {"semantic_values": values, "evidence": evidences, "attempts": attempts}, {"runtime_error": any(item["runtime_error"] for item in attempts)}


def _probe_contract_016(client: Any, store: ExperimentStore, ledger: ModelLedger015, family: PythonFamily009,
                        selected: PythonFamily009, contract: Mapping[str, Any], *, oracle: bool, seed: int) -> dict[str, Any]:
    semantic = semantic_ground_truth_016(family) if oracle else contract.get("semantic", {})
    prompt = PROBE_PROMPT_TEMPLATE_016.format(documentation=selected.api_docs, semantic_contract=canonical_json_016(semantic))
    arm = "oracle_probe" if oracle else "extracted_probe"
    payload, telemetry = _safe_model_json_016(client, store, ledger, kind=f"air-016:{arm}:{family.family_id}", prompt=prompt,
                                               max_tokens=384, seed=seed, arm=arm, prompt_version=PROBE_PROMPT_VERSION_016,
                                               prompt_sha256=PROBE_PROMPT_HASH_016, metadata={"family_id": family.family_id, "oracle": oracle})
    body = payload.get("semantic_body") if payload and isinstance(payload.get("semantic_body"), str) else None
    candidate = None
    static_pass = False
    public_pass = False
    error = None
    if body:
        try:
            candidate = build_structured_candidate_015(family, body)
            static = __import__("air_core.exp009", fromlist=["static_check_python_009"]).static_check_python_009(candidate, family)
            static_pass = static.passed
            public = run_python_gate_009(candidate, family, family.discovery, "oracle_probe" if oracle else "extracted_probe") if static_pass else PythonGate009("probe", 0, len(family.discovery), 0.0)
            public_pass = public.accuracy == 1.0
            error = None if public_pass else "public probe failed"
        except (ValueError, TypeError) as exc:
            error = str(exc)
    else:
        error = telemetry["runtime_error"] or "missing semantic_body"
    return {"oracle": oracle, "candidate_created": candidate is not None, "static_pass": static_pass,
            "public_pass": public_pass, "success": public_pass, "error": error, **telemetry}


def _arm_summary_016(rows: Sequence[Mapping[str, Any]], arm: str) -> dict[str, Any]:
    group = [row["arms"][arm] for row in rows]
    retrieval = sum(bool(row["retrieval"]["correct"]) for row in rows)
    complete = sum(bool(item.get("contract", {}).get("complete_valid")) for item in group)
    structural_fields = ("module", "callable", "signature", "input_type", "output_type", "allowed_imports", "allowed_calls", "deterministic", "side_effects")
    def mean_field(name: str) -> float:
        accuracy_key = "structural_accuracy" if name in structural_fields else "semantic_accuracy"
        values = [float(item.get("contract", {}).get(accuracy_key, {}).get(name, False)) for item in group]
        return statistics.mean(values) if values else 0.0
    structural_fields = ("module", "callable", "signature", "input_type", "output_type", "allowed_imports", "allowed_calls")
    return {
        "families_attempted": len(group), "correct_retrieval": retrieval,
        "complete_contracts": complete, "complete_valid_contract_rate": complete / retrieval if retrieval else 0.0,
        "critical_field_accuracy": statistics.mean(float(item.get("contract", {}).get("critical_field_accuracy", 0.0)) for item in group) if group else 0.0,
        "field_level_accuracy": {name: mean_field(name) for name in (*structural_fields, *SEMANTIC_FIELDS_016)},
        "module_accuracy": mean_field("module"), "callable_accuracy": mean_field("callable"),
        "import_accuracy": mean_field("allowed_imports"), "signature_accuracy": mean_field("signature"),
        "input_type_accuracy": mean_field("input_type"), "output_type_accuracy": mean_field("output_type"),
        "allowed_call_accuracy": mean_field("allowed_calls"), "invariant_accuracy": mean_field("semantic_invariants"),
        "semantic_operation_accuracy": mean_field("operation_summary"),
        "hallucinated_fields": sum(len(item.get("contract", {}).get("unknown_fields", [])) for item in group),
        "unsupported_inference_count": sum(int(item.get("contract", {}).get("unsupported_claims", 0)) for item in group),
        "evidence_supported_claim_rate": (
            sum(sum(bool(value) for value in item.get("contract", {}).get("evidence_correct", {}).values()) for item in group) /
            sum(len(item.get("contract", {}).get("evidence_correct", {})) for item in group)
            if sum(len(item.get("contract", {}).get("evidence_correct", {})) for item in group) else None
        ),
        "wrong_evidence_count": sum(sum(not bool(value) for value in item.get("contract", {}).get("evidence_correct", {}).values()) for item in group),
        "partial_contracts": sum(item.get("contract", {}).get("state") == "PARTIAL" for item in group),
        "structural_only_contracts": sum(item.get("contract", {}).get("state") == "STRUCTURAL_ONLY" for item in group),
        "malformed_outputs": sum(bool(item.get("contract", {}).get("malformed")) for item in group),
        "unknown_abstentions": sum(int(item.get("contract", {}).get("unknown_or_abstentions", 0)) for item in group),
        "oracle_downstream_success": sum(bool(item.get("oracle_probe", {}).get("success")) for item in group),
        "extracted_downstream_success": sum(bool(item.get("extracted_probe", {}).get("success")) for item in group),
        "model_calls_per_complete_contract": (
            sum(int(item.get("model_calls", 0)) for item in group) / complete if complete else None
        ),
    }


def run_contract_induction_block_016(client: LlamaCppClient, store: ExperimentStore, ledger: ModelLedger015,
                                     *, checkpoint: str | None = None, resume: Mapping[str, Any] | None = None) -> dict[str, Any]:
    families = make_contract_families_016()
    previous = {row.get("family_id"): row for row in (resume or {}).get("results", []) if isinstance(row, dict)}
    rows: list[dict[str, Any]] = []
    for index, family in enumerate(families, 1):
        if family.family_id in previous:
            rows.append(previous[family.family_id])
            continue
        pool, correct_id = make_document_pool_012(family, 10, ROBUSTNESS_SEEDS_012[0] if "1201" in family.family_id else 1202)
        retrieval_prompt = _retrieval_prompt_012(family, pool)
        payload, retrieval_telemetry = _safe_model_json_016(client, store, ledger, kind=f"air-016:retrieval:{family.family_id}",
                                                            prompt=retrieval_prompt, max_tokens=96, seed=5100 + index, arm="shared",
                                                            prompt_version=RETRIEVAL_PROMPT_VERSION_011, prompt_sha256=RETRIEVAL_PROMPT_HASH_011,
                                                            metadata={"family_id": family.family_id})
        selected_id = payload.get("doc_id") if payload and isinstance(payload.get("doc_id"), str) else None
        retrieval_correct = selected_id == correct_id
        selected = _family_selected_doc_012(family, pool, selected_id)
        ground_truth = semantic_ground_truth_016(family)
        arm_results: dict[str, Any] = {}
        baseline_payload, baseline_telemetry = _run_baseline_contract_016(client, store, ledger, family, selected, 5200 + index)
        baseline_semantic = _legacy_semantic_payload_016(baseline_payload)
        arm_results["A_free_form"] = {"contract": _canonicalize_016(arm="A_free_form", family=family, payload=baseline_payload,
                                                                      semantic_values=baseline_semantic, semantic_evidence={}, doc_id=correct_id,
                                                                      documentation=selected.api_docs, malformed=baseline_payload is None),
                                      "attempts": [{"payload": baseline_payload, **baseline_telemetry}], "model_calls": 1}
        one_payload, one_telemetry = _run_one_shot_016(client, store, ledger, family, selected, 5300 + index)
        one_semantic = _legacy_semantic_payload_016(one_payload)
        arm_results["B_structured_one_shot"] = {"contract": _canonicalize_016(arm="B_structured_one_shot", family=family, payload=one_payload,
                                                                                 semantic_values=one_semantic, semantic_evidence={}, doc_id=correct_id,
                                                                                 documentation=selected.api_docs, malformed=one_payload is None),
                                                 "attempts": [{"payload": one_payload, **one_telemetry}], "model_calls": 1}
        for arm, evidence_mode, base_seed in (("C_field_by_field", False, 5400), ("D_evidence_grounded", True, 5500)):
            field_result, field_meta = _run_field_arm_016(client, store, ledger, family, selected, base_seed + index, evidence_mode)
            arm_results[arm] = {"contract": _canonicalize_016(arm=arm, family=family, payload={"field": "field_by_field"},
                                                                semantic_values=field_result["semantic_values"], semantic_evidence=field_result["evidence"],
                                                                doc_id=correct_id, documentation=selected.api_docs,
                                                                malformed=any(item["payload"] is None for item in field_result["attempts"])),
                                "attempts": field_result["attempts"], "model_calls": len(field_result["attempts"])}
        oracle_probe = _probe_contract_016(client, store, ledger, family, selected, {"semantic": ground_truth}, oracle=True, seed=5600 + index)
        for arm in ARMS_016:
            contract = arm_results[arm]["contract"]
            extracted_probe = _probe_contract_016(client, store, ledger, family, selected, contract, oracle=False, seed=5700 + index) if contract["complete_valid"] else {
                "oracle": False, "candidate_created": False, "static_pass": False, "public_pass": False, "success": False,
                "error": "contract not complete; probe skipped", "elapsed_seconds": 0.0, "prompt_tokens": 0, "generated_tokens": 0, "runtime_error": None,
            }
            arm_results[arm]["oracle_probe"] = oracle_probe
            arm_results[arm]["extracted_probe"] = extracted_probe
            arm_results[arm]["wrong_activation"] = False
            arm_results[arm]["retrieval_correct"] = retrieval_correct
        rows.append({
            "family_id": family.family_id, "generation_seed": _family_generation_seed_016(family),
            "semantic_rule_hash": hashlib.sha256(canonical_json_016(ground_truth).encode()).hexdigest(),
            "documentation_hash": hashlib.sha256(selected.api_docs.encode()).hexdigest(),
            "package_source_hash": hashlib.sha256(Path(air_synth_012.__file__).read_bytes()).hexdigest(),
            "retrieval": {"expected_doc_id": correct_id, "selected_doc_id": selected_id, "correct": retrieval_correct, **retrieval_telemetry},
            "ground_truth_contract": {"structural": structural_metadata_016(family).to_dict(), "semantic": ground_truth},
            "arms": arm_results,
        })
        if checkpoint:
            Path(checkpoint).write_text(json.dumps({"version": EXP016_VERSION, "results": rows}, ensure_ascii=False, indent=2), encoding="utf-8")
    summary = {"families_attempted": len(rows), "results": rows, "correct_retrieval": sum(row["retrieval"]["correct"] for row in rows)}
    for arm in ARMS_016:
        summary[arm] = _arm_summary_016(rows, arm)
    return summary


def run_exp016(*, client: LlamaCppClient, store: ExperimentStore, report_directory: str,
               resume_from: str | None = None) -> dict[str, Any]:
    report_dir = Path(report_directory)
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / datetime.now(UTC).strftime("air-016-%Y%m%dT%H%M%SZ.json")
    resume = json.loads(Path(resume_from).read_text(encoding="utf-8")) if resume_from else None
    ledger = ModelLedger015()
    block = run_contract_induction_block_016(client, store, ledger, checkpoint=str(report_path), resume=resume)
    failure_counts = {key: 0 for key in FAILURE_TAXONOMY_016}
    for row in block["results"]:
        if not row["retrieval"]["correct"]:
            failure_counts["retrieval_failure"] += 1
        for arm in ARMS_016:
            contract = row["arms"][arm]["contract"]
            if contract["malformed"]:
                failure_counts["schema_failure"] += 1
            elif not all(contract["structural_accuracy"].values()):
                failure_counts["structural_metadata_failure"] += 1
            elif not contract["complete_valid"]:
                failure_counts["incomplete_contract"] += 1
            if contract["unsupported_claims"]:
                failure_counts["unsupported_claim_failure"] += contract["unsupported_claims"]
            failure_counts["semantic_extraction_failure"] += sum(
                not bool(value) for value in contract.get("semantic_accuracy", {}).values()
            )
            if arm == "D_evidence_grounded":
                failure_counts["evidence_failure"] += sum(
                    not bool(value) for value in contract.get("evidence_correct", {}).values()
                )
            if row["arms"][arm]["oracle_probe"].get("error"):
                failure_counts["oracle_downstream_failure"] += 1
            if contract["complete_valid"] and row["arms"][arm]["extracted_probe"].get("error"):
                failure_counts["extracted_contract_downstream_failure"] += 1
    summaries = {arm: block[arm] for arm in ARMS_016}
    report: dict[str, Any] = {
        "benchmark": "air-016-reliable-contract-induction-from-novel-documentation",
        "version": EXP016_VERSION, "created_at": datetime.now(UTC).isoformat(),
        "model": {"identity": MODEL_IDENTITY_016, "context_size": CONTEXT_SIZE_016, "model_parameter_update": False, "model_swap": False},
        "protocol": {
            "retrieval_frozen": True, "storage_frozen": True, "fingerprint_frozen": True,
            "sandbox_verifier_frozen": True, "exp015_synthesis_frozen": True, "family_specific_prompt": False,
            "families": 8, "new_families_beyond_0015": 3, "semantic_fields": list(SEMANTIC_FIELDS_016),
            "critical_fields": list(CRITICAL_FIELDS_016), "schema_version": CONTRACT_SCHEMA_VERSION_016,
            "arm_a_baseline_prompt": {"version": CONTRACT_PROMPT_VERSION_015, "sha256": CONTRACT_PROMPT_HASH_015, "frozen": True},
            "arm_b_prompt": {"version": STRUCTURED_SEMANTIC_PROMPT_VERSION_016, "sha256": STRUCTURED_SEMANTIC_PROMPT_HASH_016, "frozen": True},
            "arm_c_prompt": {"version": FIELD_PROMPT_VERSION_016, "sha256": FIELD_PROMPT_HASH_016, "frozen": True},
            "arm_d_prompt": {"version": EVIDENCE_PROMPT_VERSION_016, "sha256": EVIDENCE_PROMPT_HASH_016, "frozen": True},
            "downstream_probe_prompt": {"version": PROBE_PROMPT_VERSION_016, "sha256": PROBE_PROMPT_HASH_016, "frozen": True},
            "retrieval_prompt_version": RETRIEVAL_PROMPT_VERSION_011, "retrieval_prompt_sha256": RETRIEVAL_PROMPT_HASH_011,
            "timeout_is_result": True, "silent_retry": False, "hidden_ground_truth_in_prompt": False,
        },
        "acquisition": block, "arms": summaries, "failure_taxonomy": list(FAILURE_TAXONOMY_016),
        "failure_counts": failure_counts, "model_accounting": ledger.summary(),
        "comparison": {
            "0015_baseline_complete_valid_contract_rate": 0.0,
            "A_to_B_complete_contract_gain": summaries["B_structured_one_shot"]["complete_valid_contract_rate"] - summaries["A_free_form"]["complete_valid_contract_rate"],
            "B_to_C_complete_contract_gain": summaries["C_field_by_field"]["complete_valid_contract_rate"] - summaries["B_structured_one_shot"]["complete_valid_contract_rate"],
            "C_to_D_complete_contract_gain": summaries["D_evidence_grounded"]["complete_valid_contract_rate"] - summaries["C_field_by_field"]["complete_valid_contract_rate"],
            "structural_metadata_model_error_removed": summaries["B_structured_one_shot"]["module_accuracy"] == 1.0 and summaries["B_structured_one_shot"]["callable_accuracy"] == 1.0,
            "field_by_field_more_reliable_than_one_shot": summaries["C_field_by_field"]["complete_valid_contract_rate"] > summaries["B_structured_one_shot"]["complete_valid_contract_rate"],
            "evidence_reduced_unsupported_claims": summaries["D_evidence_grounded"]["unsupported_inference_count"] < summaries["C_field_by_field"]["unsupported_inference_count"],
        },
        "regression": {
            "base_library_immutable": True,
            "wrong_activation": sum(bool(row["arms"][arm]["wrong_activation"]) for row in block["results"] for arm in ARMS_016),
            "sandbox_boundary_unchanged": True, "verifier_unchanged": True,
        },
        "interpretation": {
            "bounded_contract_induction_not_continual_learning": True,
            "largest_failure_bucket": max(failure_counts, key=failure_counts.get) if any(failure_counts.values()) else "none",
            "level_3": "not evaluated; contract induction alone is insufficient",
            "next_experiment": "choose only after reviewing this failure taxonomy",
        },
        "verification": {"full_test_suite": "run externally before release", "commit_hash": os.getenv("AIR_COMMIT_SHA", "not_available_in_runtime")},
    }
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    report["report_file"] = str(report_path)
    return report


def load_checkpoint_016(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


__all__ = [
    "EXP016_VERSION", "MODEL_IDENTITY_016", "CONTEXT_SIZE_016", "ARMS_016", "SEMANTIC_FIELDS_016",
    "CRITICAL_FIELDS_016", "FAILURE_TAXONOMY_016", "CONTRACT_LIFECYCLE_016",
    "CONTRACT_SCHEMA_VERSION_016", "CONTRACT_PROMPT_HASH_015", "STRUCTURED_SEMANTIC_PROMPT_HASH_016",
    "FIELD_PROMPT_HASH_016", "EVIDENCE_PROMPT_HASH_016", "PROBE_PROMPT_HASH_016",
    "StructuralMetadata016", "Evidence016", "CanonicalContract016", "canonical_json_016",
    "structural_metadata_016", "semantic_ground_truth_016", "make_contract_families_016",
    "semantic_field_correct_016", "run_contract_induction_block_016", "run_exp016", "load_checkpoint_016",
]
